description = "Ada France Web Site"
name = "adafrance"
version = "1.14.0"
authors = ["Stephane.Carrez@gmail.com"]
licenses = "Apache-2.0"
maintainers = ["Stephane.Carrez@gmail.com"]
maintainers-logins = ["stcarrez"]
project-files = ["adafr.gpr"]
tags = ["web", "blog", "wiki"]
website = "https://gitlab.com/stcarrez/atlas"
executables = ["adafr-server"]
long-description = """

The [Ada France](https://www.ada-france.org) web site allows the
Ada France association to share information with its members and manage
their membership.  It is implemented on top of
the [Ada Web Application](https://github.com/stcarrez/ada-awa) framework.

This version of the Ada France application is using the SQLite database
so that it is easier to play with it.  Another version is using MariaDB
for production.
"""

[[depends-on]]
awa = "^2.4.0"
servletada_aws = "any"
ado_sqlite = "^2.3.0"
dynamo = "1.3.0"
excel_writer = "17.0.1"

[configuration]
disabled = true
