/* Setup permission */
INSERT INTO `awa_permission` VALUES (1,'url');
INSERT INTO `awa_permission` VALUES (2,'blog-create');
INSERT INTO `awa_permission` VALUES (3,'blog-delete');
INSERT INTO `awa_permission` VALUES (4,'blog-create-post');
INSERT INTO `awa_permission` VALUES (5,'blog-delete-post');
INSERT INTO `awa_permission` VALUES (6,'blog-update-post');
INSERT INTO `awa_permission` VALUES (7,'storage-create');
INSERT INTO `awa_permission` VALUES (8,'storage-delete');
INSERT INTO `awa_permission` VALUES (9,'folder-create');
INSERT INTO `awa_permission` VALUES (10,'workspace-create');
INSERT INTO `awa_permission` VALUES (11,'wiki-page-create');
INSERT INTO `awa_permission` VALUES (12,'wiki-page-delete');
INSERT INTO `awa_permission` VALUES (13,'wiki-page-update');
INSERT INTO `awa_permission` VALUES (14,'wiki-page-view');
INSERT INTO `awa_permission` VALUES (15,'wiki-space-create');
INSERT INTO `awa_permission` VALUES (16,'wiki-space-delete');
INSERT INTO `awa_permission` VALUES (17,'wiki-space-update');
INSERT INTO `awa_permission` VALUES (18,'anonymous');
INSERT INTO `awa_permission` VALUES (19,'logged-user');
INSERT INTO `awa_permission` VALUES (20,'workspaces-create');
INSERT INTO `awa_permission` VALUES (21,'blog-add-comment');
INSERT INTO `awa_permission` VALUES (22,'blog-publish-comment');
INSERT INTO `awa_permission` VALUES (23,'blog-delete-comment');
INSERT INTO `awa_permission` VALUES (24,'workspace-invite-user');
INSERT INTO `awa_permission` VALUES (25,'workspace-delete-user');
INSERT INTO `awa_permission` VALUES (26,'member-view');
INSERT INTO `awa_permission` VALUES (27,'member-update');
INSERT INTO `awa_permission` VALUES (28,'member-create');

/* Setup ACL for super admin */
INSERT INTO `awa_acl` VALUES (1,1,0,1,1,(SELECT id from ado_entity_type where name = 'awa_workspace'),2);
INSERT INTO `awa_acl` VALUES (2,1,0,1,1,(SELECT id from ado_entity_type where name = 'awa_workspace'),7);
INSERT INTO `awa_acl` VALUES (3,1,0,1,1,(SELECT id from ado_entity_type where name = 'awa_workspace'),8);
INSERT INTO `awa_acl` VALUES (4,1,0,1,1,(SELECT id from ado_entity_type where name = 'awa_workspace'),9);
INSERT INTO `awa_acl` VALUES (5,1,0,1,1,(SELECT id from ado_entity_type where name = 'awa_workspace'),15);
INSERT INTO `awa_acl` VALUES (8,1,0,1,1,(SELECT id from ado_entity_type where name = 'awa_blog'),3);
INSERT INTO `awa_acl` VALUES (9,1,0,1,1,(SELECT id from ado_entity_type where name = 'awa_blog'),4);
INSERT INTO `awa_acl` VALUES (10,1,0,1,1,(SELECT id from ado_entity_type where name = 'awa_blog'),5);
INSERT INTO `awa_acl` VALUES (11,1,0,1,1,(SELECT id from ado_entity_type where name = 'awa_blog'),6);
INSERT INTO `awa_acl` VALUES (12,1,0,1,1,(SELECT id from ado_entity_type where name = 'awa_blog'),21);
INSERT INTO `awa_acl` VALUES (13,1,0,1,1,(SELECT id from ado_entity_type where name = 'awa_blog'),22);
INSERT INTO `awa_acl` VALUES (14,1,0,1,1,(SELECT id from ado_entity_type where name = 'awa_blog'),23);
INSERT INTO `awa_acl` VALUES (15,1,0,1,1,(SELECT id from ado_entity_type where name = 'awa_wiki_space'),11);
INSERT INTO `awa_acl` VALUES (16,1,0,1,1,(SELECT id from ado_entity_type where name = 'awa_wiki_space'),12);
INSERT INTO `awa_acl` VALUES (17,1,0,1,1,(SELECT id from ado_entity_type where name = 'awa_wiki_space'),13);
INSERT INTO `awa_acl` VALUES (18,1,0,1,1,(SELECT id from ado_entity_type where name = 'awa_wiki_space'),14);
INSERT INTO `awa_acl` VALUES (19,1,0,1,1,(SELECT id from ado_entity_type where name = 'awa_wiki_space'),16);
INSERT INTO `awa_acl` VALUES (20,1,0,1,1,(SELECT id from ado_entity_type where name = 'awa_wiki_space'),17);
INSERT INTO `awa_acl` VALUES (21,1,0,1,1,(SELECT id from ado_entity_type where name = 'awa_workspace'),24);
INSERT INTO `awa_acl` VALUES (22,1,0,1,1,(SELECT id from ado_entity_type where name = 'awa_workspace'),25);
INSERT INTO `awa_acl` VALUES (23,1,0,1,1,(SELECT id from ado_entity_type where name = 'awa_workspace'),26);
INSERT INTO `awa_acl` VALUES (24,1,0,1,1,(SELECT id from ado_entity_type where name = 'awa_workspace'),27);
INSERT INTO `awa_acl` VALUES (25,1,0,1,1,(SELECT id from ado_entity_type where name = 'awa_workspace'),28);

INSERT INTO `ado_sequence` VALUES ('awa_acl',1,101,100);
INSERT INTO `ado_sequence` VALUES ('awa_blog',1,101,100);
INSERT INTO `ado_sequence` VALUES ('awa_email',1,101,100);
INSERT INTO `ado_sequence` VALUES ('awa_user',1,101,100);
INSERT INTO `ado_sequence` VALUES ('awa_wiki_space',1,101,100);
INSERT INTO `ado_sequence` VALUES ('awa_workspace',1,601,100);
INSERT INTO `ado_sequence` VALUES ('awa_workspace_member',1,601,100);

INSERT INTO `awa_blog` VALUES (1,'Ada France',1,'8628f625c0602f47396ea8013da3411674243a11','2017-05-17 16:16:10','1901-01-01 23:00:00','https://www.ada-france.org',1,'/adafr/images/AdaFrance-small.png',1);
INSERT INTO `awa_wiki_space` VALUES (1,'Ada France',0,3,'2017-05-17 16:12:13','','',4,1);
INSERT INTO `awa_workspace` VALUES (1,1,'2017-05-17 16:12:04',1);
INSERT INTO `awa_workspace_member` VALUES (1,'2017-05-17 16:12:04','Admin',1,1);
INSERT INTO `awa_email` VALUES ('admin@ada-france.org', 0, '1901-01-01 23:00:00.00', 1, 1, 1);
INSERT INTO `awa_user` VALUES('Admin', '', '', 'Admin', 1, 1, 1, 1);
INSERT INTO `awa_authenticate` VALUES(1, 1, 'admin@ada-france.org', '3CJkIMsK/TSSTpVnnwUf1irOQH4=', 'qPnDIWMGFg2IVCZAL8dRvvYbcuM=', 0, 1, 1);
